
package view;
import domain.*; 
import javax.swing.JOptionPane;

public class FrmPrincipal extends javax.swing.JFrame {
    boolean interesesPagados =false; 
    
    Cheques cheques ; 
    Ahorros ahorros; 
    
    public FrmPrincipal() {
        initComponents(); 
        setLocationRelativeTo(null);
    }
    public void disableTransferenciaCH (boolean activar){
        txtChfld_saldo.setEnabled(activar) ;
        btnCh_depositar.setEnabled(activar); 
        btnCh_consultar.setEnabled(activar); 
        btnCh_retirar.setEnabled(activar); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panel_registroCHEQUE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtChfld_numC = new javax.swing.JTextField();
        txtChfld_name = new javax.swing.JTextField();
        txtChfld_saldoP = new javax.swing.JTextField();
        txtChfld_comision = new javax.swing.JTextField();
        btnCh_registrar = new javax.swing.JButton();
        panelCh_transferencia = new javax.swing.JPanel();
        btnCh_depositar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtChfld_saldo = new javax.swing.JTextField();
        btnCh_retirar = new javax.swing.JButton();
        btnCh_consultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        panel_registroAHORRO = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAhfld_saldoP = new javax.swing.JTextField();
        txtAhfld_name = new javax.swing.JTextField();
        txtAhfld_numc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAhfld_fechaV = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAhfld_porcemensual = new javax.swing.JFormattedTextField();
        btnAh_registrar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtAhfld_saldo = new javax.swing.JTextField();
        btnAh_depositar = new javax.swing.JButton();
        btnAh_consultar = new javax.swing.JButton();
        btnAh_depositarInteres = new javax.swing.JButton();
        btnAh_retirarS = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtAhfld_dia = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        label_numC = new javax.swing.JLabel();
        label_nameC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuenta Cliente");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cheque ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        panel_registroCHEQUE.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Cheque"));

        jLabel1.setText("Nº Cuenta");

        jLabel2.setText("Nombre Cliente");

        jLabel3.setText("Saldo");

        jLabel4.setText("Comision");

        txtChfld_saldoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChfld_saldoPActionPerformed(evt);
            }
        });

        btnCh_registrar.setText("Registrar");
        btnCh_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCh_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_registroCHEQUELayout = new javax.swing.GroupLayout(panel_registroCHEQUE);
        panel_registroCHEQUE.setLayout(panel_registroCHEQUELayout);
        panel_registroCHEQUELayout.setHorizontalGroup(
            panel_registroCHEQUELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroCHEQUELayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_registroCHEQUELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_registroCHEQUELayout.createSequentialGroup()
                        .addGroup(panel_registroCHEQUELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_registroCHEQUELayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtChfld_saldoP, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_registroCHEQUELayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtChfld_name, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_registroCHEQUELayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChfld_numC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChfld_comision, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_registroCHEQUELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCh_registrar)
                .addContainerGap())
        );
        panel_registroCHEQUELayout.setVerticalGroup(
            panel_registroCHEQUELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroCHEQUELayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_registroCHEQUELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtChfld_numC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChfld_comision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_registroCHEQUELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChfld_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panel_registroCHEQUELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtChfld_saldoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCh_registrar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelCh_transferencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Transferencia Cheque"));
        panelCh_transferencia.setDoubleBuffered(false);

        btnCh_depositar.setText("Despositar");
        btnCh_depositar.setEnabled(false);
        btnCh_depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCh_depositarActionPerformed(evt);
            }
        });

        jLabel9.setText("Saldo ");

        txtChfld_saldo.setEnabled(false);

        btnCh_retirar.setText("Retirar ");
        btnCh_retirar.setEnabled(false);
        btnCh_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCh_retirarActionPerformed(evt);
            }
        });

        btnCh_consultar.setText("Consultar Cuenta");
        btnCh_consultar.setEnabled(false);
        btnCh_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCh_consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCh_transferenciaLayout = new javax.swing.GroupLayout(panelCh_transferencia);
        panelCh_transferencia.setLayout(panelCh_transferenciaLayout);
        panelCh_transferenciaLayout.setHorizontalGroup(
            panelCh_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCh_transferenciaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChfld_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCh_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCh_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(btnCh_retirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCh_depositar, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCh_transferenciaLayout.setVerticalGroup(
            panelCh_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCh_transferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCh_transferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtChfld_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCh_depositar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCh_retirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnCh_consultar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_registroCHEQUE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCh_transferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_registroCHEQUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCh_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuenta Cheque", jPanel2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuenta Ahorro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        panel_registroAHORRO.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Cuenta Ahorro"));

        jLabel10.setText("Nº Cuenta ");

        jLabel11.setText("Nombre Cliente");

        jLabel12.setText("Saldo");

        jLabel14.setText("Fecha de Vencimiento");

        txtAhfld_fechaV.setText("04/09/2002");

        jLabel15.setText("Porcentaje Mensual ");

        txtAhfld_porcemensual.setText("30");

        btnAh_registrar.setText("Registrar Cuenta");
        btnAh_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAh_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_registroAHORROLayout = new javax.swing.GroupLayout(panel_registroAHORRO);
        panel_registroAHORRO.setLayout(panel_registroAHORROLayout);
        panel_registroAHORROLayout.setHorizontalGroup(
            panel_registroAHORROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_registroAHORROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                        .addGap(0, 391, Short.MAX_VALUE)
                        .addComponent(btnAh_registrar))
                    .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAhfld_saldoP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                        .addGroup(panel_registroAHORROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAhfld_numc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAhfld_name, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(panel_registroAHORROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAhfld_fechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(3, 3, 3)
                                .addComponent(txtAhfld_porcemensual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panel_registroAHORROLayout.setVerticalGroup(
            panel_registroAHORROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel_registroAHORROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAhfld_numc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtAhfld_fechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_registroAHORROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_registroAHORROLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_registroAHORROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtAhfld_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtAhfld_porcemensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_registroAHORROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtAhfld_saldoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_registroAHORROLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAh_registrar)
                        .addContainerGap())))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Transferencia Cuenta Ahorro"));

        jLabel16.setText("Saldo");

        btnAh_depositar.setText("Depositar Saldo");
        btnAh_depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAh_depositarActionPerformed(evt);
            }
        });

        btnAh_consultar.setText("Consultar Cuenta");
        btnAh_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAh_consultarActionPerformed(evt);
            }
        });

        btnAh_depositarInteres.setText("Depositar Intereses");
        btnAh_depositarInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAh_depositarInteresActionPerformed(evt);
            }
        });

        btnAh_retirarS.setText("Retirar Saldo");
        btnAh_retirarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAh_retirarSActionPerformed(evt);
            }
        });

        jLabel17.setText("Dia Fecha");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtAhfld_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAhfld_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAh_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAh_depositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAh_depositarInteres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAh_retirarS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnAh_depositar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAh_depositarInteres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAh_retirarS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAh_consultar))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtAhfld_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtAhfld_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel_registroAHORRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_registroAHORRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cuenta Ahorro", jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion Cuenta", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        label_nameC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(label_nameC, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_numC, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nameC, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_numC, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCh_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCh_registrarActionPerformed
        // TODO add your handling code here: 
        
     try {
         if(!txtChfld_name.getText().equals("")&&
            !txtChfld_numC.getText().equals("")&&
            !txtChfld_saldoP.getText().equals("")&&
            !txtChfld_comision.getText().equals("")
                 ){
                   cheques = new Cheques(Integer.parseInt(txtChfld_numC.getText())
                           ,txtChfld_name.getText(),Double.parseDouble(txtChfld_saldoP.getText())
                           ,Double.parseDouble(txtChfld_comision.getText()));
            JOptionPane.showMessageDialog(null, "Se ha registrado Correctamente!");
            label_nameC.setText("Nombre Cliente:"+cheques.getNombreCliente()); 
            label_numC.setText("Nº"+String.valueOf(cheques.getNumeroCuenta())); 
             disableTransferenciaCH(true); 
            
         }
         else JOptionPane.showMessageDialog(null, "Llene los Campos Vacios!");
         
     }catch (Exception e){
         JOptionPane.showMessageDialog(null,"Ha Ocurrido un Eror ,"+e.getMessage());
     }   
   
    }//GEN-LAST:event_btnCh_registrarActionPerformed

    private void txtChfld_saldoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChfld_saldoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChfld_saldoPActionPerformed

    private void btnCh_depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCh_depositarActionPerformed
        // TODO add your handling code here: 
        try{
            if(!txtChfld_saldo.getText().equals("")){
             cheques.depositarSaldo(Double.parseDouble(txtChfld_saldo.getText()));
                JOptionPane.showMessageDialog(null, "Se ha depositado Correctamente a la Cuenta");
            }   
            else JOptionPane.showMessageDialog(null, "Llene los campos Vacios");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ha Ocurrido un Eror ,"+e.getMessage());
        }
              
    }//GEN-LAST:event_btnCh_depositarActionPerformed

    private void btnCh_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCh_retirarActionPerformed

         try{
            if(!txtChfld_saldo.getText().equals("")){
             cheques.retirarSaldo(Double.parseDouble(txtChfld_saldo.getText()));
            JOptionPane.showMessageDialog(null, "Se ha retirado Correctamente a la Cuenta");
            }  
            else JOptionPane.showMessageDialog(null, "Llene los campos Vacios");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ha Ocurrido un Eror ,"+e.getMessage());
        }
    }//GEN-LAST:event_btnCh_retirarActionPerformed

    private void btnAh_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAh_registrarActionPerformed
        // TODO add your handling code here:
           try {
         if(!txtAhfld_name.getText().equals("")&&
            !txtAhfld_numc.getText().equals("")&&
            !txtAhfld_porcemensual.getText().equals("")&&
            !txtAhfld_fechaV.getText().equals("") && 
            !txtAhfld_saldoP.getText().equals("") 
                 ){
                 ahorros = new Ahorros(Integer.parseInt (txtAhfld_numc.getText())
                         ,txtAhfld_name.getText(),Double.parseDouble(txtAhfld_saldoP.getText())
                         ,Integer.parseInt(txtAhfld_porcemensual.getText()));
                 ahorros.setFechaVencimiento(txtAhfld_fechaV.getText()); 
                
                 
            JOptionPane.showMessageDialog(null, "Se ha registrado Correctamente!");
            label_nameC.setText("Nombre Cliente : "+ahorros.getNombreCliente()); 
            label_numC.setText("Nº: "+String.valueOf(ahorros.getNumeroCuenta()));
         }
         else JOptionPane.showMessageDialog(null, "Llene los Campos Vacios!");
         
     }catch (Exception e){
         JOptionPane.showMessageDialog(null,"Ha Ocurrido un Eror ,"+e.getMessage());
     }   
       
    }//GEN-LAST:event_btnAh_registrarActionPerformed

    private void btnCh_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCh_consultarActionPerformed
        // TODO add your handling code here: 
        JOptionPane.showMessageDialog(null,cheques.toString(),"Datos Cheques"
                ,JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCh_consultarActionPerformed

    private void btnAh_depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAh_depositarActionPerformed
        // TODO add your handling code here: 
        try{
            if(!txtAhfld_saldo.getText().equals("")) {
              ahorros.depositarSaldo(Double.parseDouble(txtAhfld_saldo.getText())); 
            JOptionPane.showMessageDialog(null, "Se ha realizado la Transacion");
            }
            else JOptionPane.showMessageDialog(null, "Llene los campos Vacios");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ha Ocurrido un Eror ,"+e.getMessage());
        } 
    }//GEN-LAST:event_btnAh_depositarActionPerformed

    private void btnAh_depositarInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAh_depositarInteresActionPerformed
        // TODO add your handling code here: ç
        
        try{
            if(!txtAhfld_saldo.getText().equals("")){   
                 ahorros.depositarInteres(Double.parseDouble(txtAhfld_saldo.getText()));
            JOptionPane.showMessageDialog(null, "Se ha realizado la Transacion");
            }
            
            else JOptionPane.showMessageDialog(null, "Llene los campos Vacios");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ha Ocurrido un Eror ,"+e.getMessage());
        }
    }//GEN-LAST:event_btnAh_depositarInteresActionPerformed

    private void btnAh_retirarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAh_retirarSActionPerformed
        // TODO add your handling code here: 
        // tambien debe comprobar si esta en el dia del vencimiento 
        try {
        if(ahorros.getTotalInteres()==0.00 && (!txtAhfld_dia.getText().equals(""))   ){
            ahorros.retirarSaldo(Double.parseDouble(txtAhfld_saldo.getText()),txtAhfld_dia.getText()); 
            JOptionPane.showMessageDialog(null, "Se ha realizado la Transacion");
        } 
   
        
        else JOptionPane.showMessageDialog(null, "Llene los campos Vacios" );
        
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ha ocurrido un Error ,"+e.getMessage());
        }
    }//GEN-LAST:event_btnAh_retirarSActionPerformed

    private void btnAh_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAh_consultarActionPerformed
        // TODO add your handling code here: 
        JOptionPane.showMessageDialog(null,ahorros.toString());
    }//GEN-LAST:event_btnAh_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAh_consultar;
    private javax.swing.JButton btnAh_depositar;
    private javax.swing.JButton btnAh_depositarInteres;
    private javax.swing.JButton btnAh_registrar;
    private javax.swing.JButton btnAh_retirarS;
    private javax.swing.JButton btnCh_consultar;
    private javax.swing.JButton btnCh_depositar;
    private javax.swing.JButton btnCh_registrar;
    private javax.swing.JButton btnCh_retirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_nameC;
    private javax.swing.JLabel label_numC;
    private javax.swing.JPanel panelCh_transferencia;
    private javax.swing.JPanel panel_registroAHORRO;
    private javax.swing.JPanel panel_registroCHEQUE;
    private javax.swing.JTextField txtAhfld_dia;
    private javax.swing.JFormattedTextField txtAhfld_fechaV;
    private javax.swing.JTextField txtAhfld_name;
    private javax.swing.JTextField txtAhfld_numc;
    private javax.swing.JFormattedTextField txtAhfld_porcemensual;
    private javax.swing.JTextField txtAhfld_saldo;
    private javax.swing.JTextField txtAhfld_saldoP;
    private javax.swing.JTextField txtChfld_comision;
    private javax.swing.JTextField txtChfld_name;
    private javax.swing.JTextField txtChfld_numC;
    private javax.swing.JTextField txtChfld_saldo;
    private javax.swing.JTextField txtChfld_saldoP;
    // End of variables declaration//GEN-END:variables
}
